### ISSUE TITLE
readme里面的upload.txt备注错了，应该是0否1是

### ISSUE THREAD

**Issue by HPShark** [abadfox233/ncov#2]
默认的内容是对的，不过后面的备注错了，应该是0->否, 1->是，还好晚上抓了包看了看不然明天我就得被抓走隔离...

附抓包内容：
![image](https://user-images.githubusercontent.com/24475140/88293457-9d082300-cd2d-11ea-996a-2bb49cca2175.png)

我修改的upload内容：
{
    "sfzx": "1", # 是否在校(0->否, 1->是)
    "tw": "1", # 体温 (36℃->0, 36℃到36.5℃->1, 36.5℃到36.9℃->2, 36.9℃到37℃.3->3, 37.3℃到38℃->4, 38℃到38.5℃->5, 38.5℃到39℃->6, 39℃到40℃->7, 40℃以上->8)
    "sfcyglq": "0", # 是否处于隔离期? (0->否, 1->是)
    "sfyzz": "0", # 是否出现乏力、干咳、呼吸困难等症状？ (0->否, 1->是)
    "qtqk": "", # 其他情况 (文本)
    "askforleave": "0" # 是否请假外出? (0->否, 1->是)
}

**Comment by abadfox233** [comment]
已修改
